server:
  port: 8081

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://localhost:5433/fraud-system
    username: postgres
    password: password

  jpa:
    show-sql: true
    hibernate:
     ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE